backend:
  name: github
  repo: Dev-in-the-BM/Ctrl-Shift-Esc
  branch: Main
  base_url: https://sveltia-admin.devinthebm.workers.dev # <-- REPLACE THIS with your Cloudflare Worker URL

media_folder: 'src/assets'
public_folder: '/src/assets'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string', required: false }
      - { label: 'Excerpt', name: 'excerpt', widget: 'text', required: false }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Hero Image', name: 'heroImage', widget: 'image', required: false }
      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime', required: false }
      - { label: 'Content', name: 'body', widget: 'markdown' }
